export default {
    darkMode: "class",

    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./config/repositorio.php",
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
    ],
    safelist: [
        // Paletas autores
        "bg-indigo-100",
        "text-indigo-700",
        "dark:bg-indigo-500/20",
        "dark:text-indigo-300",
        "bg-sky-100",
        "text-sky-700",
        "dark:bg-sky-500/20",
        "dark:text-sky-300",
        "bg-teal-100",
        "text-teal-700",
        "dark:bg-teal-500/20",
        "dark:text-teal-300",
        "bg-cyan-100",
        "text-cyan-700",
        "dark:bg-cyan-500/20",
        "dark:text-cyan-300",
        "bg-blue-100",
        "text-blue-700",
        "dark:bg-blue-500/20",
        "dark:text-blue-300",
        "bg-slate-200",
        "text-slate-600",
        "dark:bg-slate-500/30",
        "dark:text-slate-300",

        // Badge informes
        "border-blue-200",
        "dark:bg-blue-500/10",
        "dark:text-blue-400",
        "bg-purple-100",
        "text-purple-700",
        "border-purple-200",
        "dark:bg-purple-500/10",
        "dark:text-purple-400",
        "bg-emerald-100",
        "text-emerald-700",
        "border-emerald-200",
        "dark:bg-emerald-500/10",
        "dark:text-emerald-400",
        "bg-amber-100",
        "text-amber-700",
        "border-amber-200",
        "dark:bg-amber-500/10",
        "dark:text-amber-400",

        // Tipo estilos publicaciones
        "bg-blue-600",
        "bg-indigo-600",
        "bg-slate-700",
        "bg-amber-500",
        "text-white",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["Nunito", "sans-serif"],
            },
            colors: {
                repository1: "#FFEC00",
                repository2: "#FFFFFF",
                repository3: "#161616",
                repository4: "#0081AF",
                repository5: "#3B60E4",
            },
            spacing: {
                "0.5px": "1px",
            },
        },
    },

    plugins: [],
};
